.TH BTFS 1
.SH NAME
btfs \- mount torrent files or magnet links as a file system
.SH SYNOPSIS
.B btfs
[\fIoptions\fP]
\fBmetadata\fP
\fBmountpoint\fP
.SH DESCRIPTION
.B btfs
allows one to mount any torrent file or a magnet link as a file
system. The contents of the files will be downloaded on-demand
as they are read by applications.
.SH OPTIONS
.TP
\fB\-v\fR   \fB\-\-version\fR
print version
.TP
\fB\-h\fR   \fB\-\-help\fR
print help
.TP
\fB\-b\fR   \fB\-\-browse-only\fR
download metadata only
.TP
\fB\-k\fR   \fB\-\-keep\fR
keep files after unmount
.TP
\fB\-\-min-port=\fIPORT\fR
start of listen port range
.TP
\fB\-\-max-port=\fIPORT\fR
end of listen port range
.TP
\fB\-\-max-download-rate=\fIRATE\fR
maximum download rate (in kilobytes per second)
.TP
\fB\-\-max-upload-rate=\fIRATE\fR
maximum upload rate (in kilobytes per second)
.SH EXAMPLES
mounting a torrent file:
  btfs video.torrent ~/mnt

mounting a magnet link:
  btfs 'magnet:?xt=urn:btih:...' ~/mnt

unmounting:
  fusermount -u ~/mnt
.SH BUGS
Please report any bugs to https://github.com/johang/btfs.
.PD
.SH "AUTHORS"
.LP
BTFS has been written by Johan Gunnarsson <johan.gunnarsson@gmail.com>
.LP
This man page was written by Donat Kh. <donat@opmbx.org>
