#!/usr/bin/env sh
# Copyright 2017 Johan Gunnarsson <johan.gunnarsson@gmail.com>
#
# This file is part of BTFS.
#
# BTFS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BTFS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with BTFS.  If not, see <http://www.gnu.org/licenses/>.

git clone --recurse-submodules -b "${1:-master}" https://github.com/arvidn/libtorrent.git &&
cd libtorrent &&
mkdir build &&
cd build &&
cmake -DCMAKE_INSTALL_PREFIX="${2:-/tmp}" -G "Unix Makefiles" .. &&
make &&
make install
